"""Configuration"""

import datetime
import logging
import os
import tomllib
from pathlib import Path

from sphinx.errors import ConfigError
from spl_core.report_generation.spl_html_settings import html_last_updated_fmt, html_show_sourcelink, html_sidebars, html_theme, html_theme_options  # noqa: F401
from spl_core.report_generation.spl_sphinx import SplSphinx

day = datetime.date.today()  # noqa: DTZ011 -- the release is the local date of the build
# meta data #################################################################

project = "SPLed"
copyright = f"{day.year}, RMT and Friends"
release = f"{day}"

# file handling #############################################################
# @see https://www.sphinx-doc.org/en/master/usage/configuration.html

templates_path = [
    "doc/_tmpl",
]

exclude_patterns = [
    "README.md",
    ".venv",
    ".git",
    "**/test_results.rst",  # We renamed this file, but nobody deletes it.
    # Directories under build/ that never hold a document: fetched dependencies,
    # the variant data, CMake's own state and the HTML the builds write.
    # get_matching_files applies these to directories as well, so each entry
    # prunes the walk. Which generated pages are documents is decided by the
    # selection (below), not here.
    "build/modules",
    "build/variants",
    "build/**/CMakeFiles",
    "build/**/html",
]

# The 150% source set of the hand-written documents: the same set ubCode's md
# parser include names in ubproject.toml. The generated pages of the selected
# build are added from the selection (below), as ubCode's rst parser include
# names them there.
#
# Which of them a build actually contains is decided by the rules in
# ubproject.variants.toml, against the variant data. Narrowing the set here as
# well would put a second, invisible gate in front of the declared one -- and an
# invisible gate is the thing this whole design exists to remove.
include_patterns = [
    "index.md",
    "doc/**",
    "components/**/doc/**",
    "test/**/doc/**",
]

# configuration of built-in stuff ###########################################
# @see https://www.sphinx-doc.org/en/master/usage/configuration.html

numfig = True

# html config ###############################################################
# @see https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# Omit "documentation" in title. Include the variant, so that a browser tab or
# the sidebar logo tells two variants' builds apart -- both otherwise render the
# same generic title and are indistinguishable when opened side by side.
_html_title_variant = os.environ.get("VARIANT", "")
html_title = f"{project} {_html_title_variant} {release}".strip() if _html_title_variant else f"{project} {release}"

html_logo = "doc/_figures/SPLED_logo.png"

# Get default SPL extensions and their configurations. The test results are
# needs.json that spl-core writes after each test run and both readers import
# (SPL_TEST_RESULTS_AS_NEEDS in CMakeLists.txt), so sphinx-test-reports' directive,
# which only Sphinx knows, is not loaded.
extensions = [
    *(extension for extension in SplSphinx.default_extensions if extension != "sphinxcontrib.test_reports"),
    "sphinx_codelinks",
    "sphinx_mounts",
]
extension_configs = SplSphinx.default_extension_configs

# sphinx-codelinks: extract one-line need definitions from source code comments
src_trace_config_from_toml = "ubproject.toml"

# Apply extension-specific configurations
myst_enable_extensions = extension_configs["myst_enable_extensions"]
source_suffix = extension_configs["source_suffix"]

# The needs model -- types, link types, fields, and the build_json switch --
# lives in ubproject.toml, which ubCode and ubc read directly. sphinx-needs
# reads exactly one TOML file and does not implement ubCode's `extend`, so the
# only way both readers can agree is for that one file to be complete. It is;
# spl-core's base configuration is vendored into it.
needs_from_toml = "ubproject.toml"

# The document rules, generated by tools/variant_data.py, one per documented
# component. sphinx-mounts reads rules from one file, relative to that file, so
# they live in a file of their own at the project root; ubproject.toml reaches
# the same file through `extend`.
sources_from_toml = "ubproject.variants.toml"

# The `results` links of the test specifications are data, written by spl-core's
# converter as needextend blocks on each results page, so no needs function and
# no computed default is registered: every need and every link is something
# ubCode reads as well.


# One warning is dropped, and only that one, for two fields. ubproject.toml has
# to declare the test results' `file` field, because ubc drops an undeclared
# field of an imported need without a word, and `remote-url`, because ubc links
# only a declared field. sphinx-codelinks registers fields of the same names,
# and sphinx-needs compares field names only, so it warns
# "Duplicate need field '<name>'" although both declarations agree. Sphinx can only
# suppress a whole warning type (`needs.config`), which would hide every other
# problem in the needs configuration; this filter matches the two messages.
# Remove it once sphinx-needs accepts a matching declaration.
_FIELDS_CODELINKS_REGISTERS_TOO = ("file", "remote-url")


class _DropTheDuplicateFieldWarning(logging.Filter):
    def filter(self, record: logging.LogRecord) -> bool:
        if getattr(record, "type", "") != "needs" or getattr(record, "subtype", "") != "config":
            return True
        try:
            message = record.getMessage()
        except (TypeError, ValueError):  # a record whose arguments do not fit its message
            return True
        return not any(f"Duplicate need field '{name}'" in message for name in _FIELDS_CODELINKS_REGISTERS_TOO)


for _handler in logging.getLogger("sphinx").handlers:
    _handler.filters.insert(0, _DropTheDuplicateFieldWarning())

# variant selection #########################################################
#
# ONE file decides what a build shows, and nothing is computed here.
#
# tools/variant_data.py writes build/selection.toml whenever a variant is
# selected: the variant data file every condition is evaluated against, and, for
# a CMake build's reports, that build's generated pages by their own paths
# (ubCode's rst parser include); for a per-component report also its root
# document. ubproject.toml
# reaches it through `extend` (by way of ubproject.variants.toml), which ubCode
# and ubc follow. sphinx-needs and sphinx-mounts each read one TOML file and do
# not follow `extend`, so this hands them the selection's keys: the same keys,
# from the same file, nothing added.
#
# The variant data file holds everything a document's {if} directive or a rule
# may name -- the complete feature vector, the variant, the build kit, the build
# target, the component list. ubCode, ubc and a reviewer's editor cannot execute
# this file, so anything synthesized here would be invisible to them, and their
# view of the project would disagree with the build.
#
# Each run spl-core starts names its own build's file (`-D spl_selection=...`,
# SPL_SPHINX_OPTIONS in CMakeLists.txt), so two builds' reports can be built side
# by side. An explicit `-D needs_variant_data_file=...` or `-D root_doc=...` still
# wins over the file, the way `-c` does for ubc:
#
#     sphinx-build -D needs_variant_data_file=build/variants/Sleep/test/docs.json ...
#
# The handler runs at config-inited priority 5: before sphinx-needs loads its
# TOML (10) and resolves the variant data (11), before sphinx-mounts loads its
# rules (400), and before Sphinx reads `include_patterns` to find the documents.

root_doc = "index"


def _load_selection(app, config):
    selection_path = Path(app.confdir) / config.spl_selection
    overrides = getattr(config, "overrides", {})
    if not selection_path.is_file():
        if "needs_variant_data_file" in overrides:
            return
        raise ConfigError(
            f"No variant is selected: {selection_path} does not exist. Configure a CMake build, "
            "or run `python tools/variant_data.py --all --current --variant <variant> --kit <kit>`."
        )
    selection = tomllib.loads(selection_path.read_text(encoding="utf-8"))
    variant_data_file = selection.get("needs", {}).get("variant_data_file")
    if variant_data_file is not None and "needs_variant_data_file" not in overrides:
        config.needs_variant_data_file = variant_data_file
    root = selection.get("project", {}).get("root_doc")
    if root is not None and "root_doc" not in overrides:
        config.root_doc = root
    pages = selection.get("parse", {}).get("parsers", {}).get("rst", {}).get("include", [])
    config.include_patterns = [*config.include_patterns, *pages]
    # A per-component report's links to the rest of the product dangle by design;
    # its selection says so in ubc's terms, and this is the same statement for
    # sphinx-needs, for that report only.
    if "needs.dead_link" in selection.get("lint", {}).get("ignore", []):
        config.suppress_warnings = [*config.suppress_warnings, "needs.link_outgoing"]


# links that sphinx-codelinks renders itself ##############################
#
# ubproject.toml declares a link rule for `remote-url`, because ubCode stores
# the whole URL there and renders a field as plain text without a rule. In
# Sphinx, sphinx-codelinks stores the path instead and adds its own rule while
# its directive runs, pinned to the commit. sphinx-needs applies only the FIRST
# rule naming a field, matching or not, and the one from ubproject.toml comes
# first, so it would leave Sphinx's path unlinked. Sphinx gets codelinks' rule
# alone: this drops the ubCode rule between sphinx-needs loading the TOML (10)
# and compiling the rules (551).


def _leave_codelinks_links_to_codelinks(app, config):
    config.needs_string_links = {name: rule for name, rule in config.needs_string_links.items() if "remote-url" not in rule.get("options", [])}


# configuration checks ######################################################
#
# The checks test_ubproject_config.py runs, run again whenever Sphinx reads this
# configuration (tools/config_checks.py): the vendored needs model against
# spl-core's, the two readers' document sets against each other, and the
# generated rules against the shared grammar. A finding is a warning, so a drift
# fails the build under -W instead of waiting for someone to run the tests.


def _check_configuration(app, config):
    import sys

    from sphinx.util import logging as sphinx_logging

    tools = str(Path(app.confdir) / "tools")
    if tools not in sys.path:
        sys.path.insert(0, tools)
    import config_checks

    logger = sphinx_logging.getLogger(__name__)
    for finding in config_checks.run_all(Path(app.confdir), list(config.include_patterns)):
        logger.warning(f"configuration check: {finding}", type="spled", subtype="config")


def setup(app):
    app.add_config_value("spl_selection", "build/selection.toml", "env", types=(str,))
    app.connect("config-inited", _load_selection, priority=5)
    app.connect("config-inited", _leave_codelinks_links_to_codelinks, priority=20)
    app.connect("config-inited", _check_configuration, priority=900)
