[project]
name = "spled"
version = "0.0.1"
description = "SPL demo project"
authors = [{ name = "Avengineers" }]
requires-python = "<3.14,>=3.12"

dependencies = [
    "spl-core @ git+https://github.com/useblocks/spl-core.git@010727d08b27ca73994772444d25d7bc6e028c31",
    "pypeline-runner>=1.33,<2",
    "pytest>=8,<9",
    "myst-parser>=4.0,<5",
    "pypeline-semantic-release>=0,<1",
    "poks>=0.9.4,<1",
    "object-deps-report>=0,<1",
    "sphinx-codelinks>=1.2,<2",
    "sphinx-mounts>=0.2,<1"
]

[tool.poetry]
package-mode = false

[tool.ruff]
line-length = 180
