[source]
exclude = [".bzr", ".direnv", ".eggs", ".git", ".git-rewrite", ".hg", ".svn", ".venv", ".vscode", "_build", "dist", "node_modules", "site-packages"]
respect_gitignore = false
extend_include = ["build/**/__source_docs/**"]

[server]
index_on_save = true
hover_need_refs = true

[parse.parsers.rst]

[parse.parsers.md]
flavour = "myst"
include = ["*.md"]

[needs]
schema_definitions_from_json = "schema.json"

variant_data_file = "build/Disco/prod/kconfig/autoconf.json"

extra_links = [
    { option = "realizes", incoming = "is realized by", outgoing = "realizes" },
    { option = "fulfills", incoming = "is fulfilled by", outgoing = "fulfills" },
    { option = "refines", incoming = "is refined by", outgoing = "refines" },
    { option = "implements", incoming = "is implemented by", outgoing = "implements" },
    { option = "results", incoming = "results from", outgoing = "results" },
    { option = "verifies", incoming = "is verified by", outgoing = "verifies" },
    { option = "tests", incoming = "is tested by", outgoing = "tests" },
    { option = "covered_by", incoming = "covers", outgoing = "covered by" },
]

# Fields

[needs.fields.status]
parse_variants = true

[needs.fields.integrity]
parse_variants = true
default = ""

# Types

[[needs.types]]
directive = "arch"
title = "Architecture"
prefix = "A_"
color = "#DF744A"
style = "node"

[[needs.types]]
directive = "req"
title = "Requirement"
prefix = "R_"
color = "#BFD8D2"
style = "node"

[[needs.types]]
directive = "spec"
title = "Specification"
prefix = "S_"
color = "#FEDCD2"
style = "node"

[[needs.types]]
directive = "impl"
title = "Implementation"
prefix = "I_"
color = "#DF744A"
style = "node"

[[needs.types]]
directive = "test"
title = "Test Case"
prefix = "T_"
color = "#DCB239"
style = "node"
