#!/usr/bin/env python3
"""Write the files that decide what every documentation tool shows.

One generation step before any reader runs, and nothing downstream needs Python
to decide anything: the rules, the `{if}` directives in the documents and the
selected build all come out of the files written here, and `sphinx-build`,
`ubc` and the ubCode language server read the same ones. The rule that follows
from that is the only one worth remembering here:

    everything a condition may name has to be IN the variant data file.

A key that only `conf.py` knows is invisible to every other reader, and their
view of the project then disagrees with the build. That is why this writes the
complete feature vector -- including the booleans KConfig omits -- plus the
build shape, rather than leaving any of it to be synthesized later.

Layout::

    build/variants/<Variant>/<kit>/<target>.json              the matrix: one variant data file per cell
    build/variants/<Variant>/<kit>/<component>/<target>.json  the same, for one component's report
    build/variants/GENERATED                                  marker; nobody edits generated output
    ubproject.variants.toml                                   the document rules, one per documented component
    build/selection.toml                                      the selected build, for the IDE and a bare run
    <build dir>/selection/[<component>/]<target>.toml         the same for each run spl-core starts there

Nothing needs maintaining by hand for a component. Its rule is derived from
where its documentation lives and gated on the variant's component list, which
comes from `parts.cmake`: adding a component is adding it to `parts.cmake` and
writing its documentation.

The rules are the same for every variant, so they live in one file, at the
project root: sphinx-mounts reads rule patterns relative to the file that
declares them and refuses absolute or `..` ones. A selection file names a
variant data file and, for a CMake build, mounts that build's directory at
`generated`, where every page spl-core generates is named. ubproject.toml
reaches both files through `extend`; conf.py hands the selection's keys to
Sphinx, whose extensions each read one TOML file and do not follow `extend`.

Nothing here needs a compiler. KConfig is pure Python, while CMake's top-level
`project()` call demands a C toolchain before it will even configure -- so with
this script the documentation and its quality gate can be built on a machine
that cannot build the software.

Usage::

    python tools/variant_data.py --all
    python tools/variant_data.py --variant Disco --kit test --target reports --current
    python tools/variant_data.py --all --check      # CI: regenerate and diff
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path
from typing import Any

#: The generated rule file, at the project root (see the module docstring).
RULES_FILE = "ubproject.variants.toml"

#: The selection the IDE and a bare `sphinx-build` or `ubc` read.
SELECTION_FILE = "build/selection.toml"

#: The root document of a per-component report.
COMPONENT_ROOT_DOC = "doc/component_report"

#: Rules written by hand, for the cases a component's membership does not decide
#: (VARIANTS.md, use case 13). Appended to the generated ones: ubproject.toml
#: cannot hold rules of its own, because `extend` replaces arrays rather than
#: merging them.
HAND_WRITTEN_RULES = "doc/variant_rules.toml"

#: Where the generated pages of the selected build appear. spl-core names every
#: page it generates below it (SPL_SPHINX_BINARY_DIR in CMakeLists.txt).
MOUNT_AT = "generated"

#: The pages a build directory contributes, relative to it: spl-core's report
#: pages and the clanguru listings. The same patterns as ubCode's rst parser
#: include in ubproject.toml; everything else in a build directory (CMake state,
#: HTML output, spl-core's navigation wrappers, fetched dependencies) stays out.
MOUNTED_PAGES = ("components/**/*.rst", "test/**/*.rst", "reports/*.rst")

GENERATED_HEADER = (
    "# GENERATED by tools/variant_data.py -- do not edit. It is rewritten whenever a\n"
    "# variant is selected, and whatever is changed here is lost.\n"
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent

#: Components a variant's `parts.cmake` adds only for the test build kit.
TEST_KIT_GUARD = "BUILD_KIT STREQUAL test"

#: The build shapes spl-core builds. `docs` is the design documentation of a
#: variant; `reports` additionally carries the generated test and coverage
#: output, which is why documents gate report sections on it.
TARGETS = ("docs", "reports")

#: The build kits. `components` differs between them, because a variant's
#: parts.cmake adds its test suites only for `test`.
KITS = ("prod", "test")


def _spl_core_dir() -> Path:
    import spl_core

    return Path(spl_core.__file__).parent


def variant_names(project_root: Path) -> list[str]:
    """Every variant in `variants/`, as the slash-separated name CMake uses.

    A variant is a directory holding a `config.cmake`; it may be one level deep
    (`Disco`) or two (`Base/Dev`), which is why this walks rather than lists.
    """
    variants_dir = project_root / "variants"
    return sorted(
        str(path.parent.relative_to(variants_dir)).replace(os.sep, "/")
        for path in variants_dir.rglob("config.cmake")
    )


def features(project_root: Path, variant: str) -> dict[str, Any]:
    """The variant's complete feature vector.

    Every boolean the feature model declares is present, defaulted to False,
    before the variant's own values are overlaid. KConfig writes a boolean into
    its JSON only when the symbol has a prompt or evaluates to y, so a helper
    symbol such as BRIGHTNESS_ADJUSTMENT_ENABLED is simply absent from the
    variants where it is off -- and a condition naming it would fail to evaluate
    for exactly those variants, which both tools then report as unevaluable and
    gate off rather than cleanly answering False.
    """
    from spl_core.kconfig.kconfig import JsonWriter, KConfig

    os.environ.setdefault("SPL_CORE_DIR", str(_spl_core_dir()))
    os.environ.setdefault("srctree", str(project_root))

    model_file = project_root / "KConfig"
    config_file = project_root / "variants" / variant / "config.txt"

    kconfig = KConfig(
        model_file,
        config_file if config_file.exists() else None,
        project_root,
    )

    # `KConfig.config` only carries the symbols KConfig would write out. The
    # model itself knows every symbol, which is what makes the vector complete.
    defaults = dict.fromkeys(kconfig.declared_boolean_symbols(), False)

    # spl-core's own JSON writer, so the value conversion (tristates to bool,
    # hex, the ${VAR} substitution) is the build's and not a second opinion.
    # `generate_content` is the pure half of it; nothing is written here.
    values = json.loads(JsonWriter(Path(os.devnull)).generate_content(kconfig.config))["features"]
    return {**defaults, **values}


def components(project_root: Path, variant: str, kit: str) -> list[str]:
    """The components the variant's `parts.cmake` adds for this build kit.

    Parsed rather than imported, because the point is to state the product
    structure once, in the file that already states it. The grammar every
    parts.cmake in this project uses is a flat list of `spl_add_component()`
    calls, optionally with one `if(BUILD_KIT STREQUAL test)` / `else()` /
    `endif()` block.

    Anything outside that grammar raises. A parser that shrugged at an `if()`
    it did not understand would treat the guarded body as unconditional and
    hand back a component list that is quietly wrong for some kit -- and since
    this list is what gates the documents, the failure would surface as
    documents silently missing from a variant, which is the hardest kind of
    wrong to notice. Better to stop and make someone either extend the grammar
    or derive the list from CMake.
    """
    parts = project_root / "variants" / variant / "parts.cmake"
    result: list[str] = []
    #: None outside any if-block, else the kit whose branch we are currently in.
    branch_kit: str | None = None
    depth = 0

    for number, raw_line in enumerate(parts.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        lowered = line.lower()
        where = f"{parts.relative_to(project_root)}:{number}"

        if lowered.startswith(("if(", "if ")):
            if depth or TEST_KIT_GUARD.lower() not in lowered:
                raise ValueError(
                    f"{where}: unsupported condition {line!r}. "
                    f"{parts.name} may only use a single, non-nested "
                    f"`if({TEST_KIT_GUARD})` block; extend the grammar in "
                    "tools/variant_data.py (and its test) deliberately."
                )
            depth += 1
            branch_kit = "test"
            continue
        if lowered.startswith(("else(", "else ", "else")) and not lowered.startswith("elseif"):
            if not depth:
                raise ValueError(f"{where}: `else()` outside any `if()`.")
            # The other side of the test-kit guard is every kit that is not test.
            branch_kit = "prod"
            continue
        if lowered.startswith("elseif"):
            raise ValueError(f"{where}: `elseif()` is not supported, see above.")
        if lowered.startswith(("endif(", "endif ", "endif")):
            if not depth:
                raise ValueError(f"{where}: `endif()` without `if()`.")
            depth -= 1
            branch_kit = None
            continue
        if lowered.startswith("spl_add_component("):
            if branch_kit is not None and branch_kit != kit:
                continue
            result.append(line[len("spl_add_component(") : line.rindex(")")].strip())
            continue

        raise ValueError(
            f"{where}: unsupported statement {line!r}. {parts.name} may only "
            "contain `spl_add_component()` calls and the test-kit guard."
        )

    if depth:
        raise ValueError(f"{parts.relative_to(project_root)}: unterminated `if()`.")

    return result


def documented_components(project_root: Path) -> list[str]:
    """Every component with documentation: a directory with a `doc/index` page.

    The same test spl-core applies before it creates a component's docs and
    report builds. Components without documentation need no rule, because they
    contribute no page.
    """
    found: set[str] = set()
    for top in ("components", "test"):
        base = project_root / top
        if not base.is_dir():
            continue
        for index in base.rglob("index.*"):
            if index.suffix in (".md", ".rst") and index.parent.name == "doc":
                found.add(index.parent.parent.relative_to(project_root).as_posix())
    return sorted(found)


def variant_data(
    project_root: Path, variant: str, kit: str, target: str, component: str | None = None
) -> dict[str, Any]:
    """One cell of the matrix: everything a condition anywhere may name.

    `component` makes it the cell of that component's report. The component list
    stays the variant's, so a block conditioned on another component's presence
    reads the same in the component's report as in the variant's documentation;
    only `scope` and `component` differ, and the rules gate the documents on them.
    """
    return {
        "features": features(project_root, variant),
        "build_config": {
            "variant": variant,
            "kit": kit,
            "target": target,
            "components": components(project_root, variant, kit),
            "scope": "component" if component else "variant",
            "component": component or "",
        },
    }


def cell_path(project_root: Path, variant: str, kit: str, target: str, component: str | None = None) -> Path:
    base = project_root / "build" / "variants" / variant / kit
    return (base / component if component else base) / f"{target}.json"


def write_cell(
    project_root: Path, variant: str, kit: str, target: str, data: dict[str, Any], component: str | None = None
) -> Path:
    path = cell_path(project_root, variant, kit, target, component)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def reported_components(project_root: Path, variant: str, kit: str) -> list[str]:
    """The components of this cell that get a per-component report."""
    documented = set(documented_components(project_root))
    return [component for component in components(project_root, variant, kit) if component in documented]


def cells(project_root: Path, variant: str) -> list[tuple[str, str, str | None]]:
    """Every (kit, target, component) cell of one variant, the component ones included."""
    result: list[tuple[str, str, str | None]] = []
    for kit in KITS:
        for target in TARGETS:
            result.append((kit, target, None))
            result.extend((kit, target, component) for component in reported_components(project_root, variant, kit))
    return result


def rules_toml(project_root: Path) -> str:
    """The document rules: which documents a variant data file admits.

    Rules are subtractive: a rule whose condition is FALSE removes the files it
    names, a TRUE rule does nothing, so two rules naming the same file compose as
    AND. Gated on membership of the variant's component list, never on the
    variant's name: the product structure is stated once, in parts.cmake.

    A per-component report (`scope == "component"`) shows one component: its own
    documentation and generated pages, under doc/component_report.md, and none of
    the variant-wide documents.
    """
    doc_dir = project_root / "doc"
    variant_wide = ["index.md"]
    for entry in sorted(doc_dir.iterdir()) if doc_dir.is_dir() else []:
        if entry.name == Path(COMPONENT_ROOT_DOC).name + ".md":
            continue
        variant_wide.append(f"doc/{entry.name}/**" if entry.is_dir() else f"doc/{entry.name}")
    variant_wide.append(f"{MOUNT_AT}/reports/**")

    def rule(condition: str, files: list[str], comment: str) -> str:
        listed = "".join(f'    "{pattern}",\n' for pattern in files)
        return f"\n# {comment}\n[[source.variant_sources]]\nif = \"{condition}\"\nfiles = [\n{listed}]\n"

    text = GENERATED_HEADER + (
        "#\n"
        "# Which documents a variant data file admits. The same for every variant; the\n"
        "# selected build comes in through the `extend` below.\n"
        "\n"
        f'extend = "{SELECTION_FILE}"\n'
    )
    text += rule("var.build_config.scope == 'variant'", variant_wide, "The variant-wide documents.")
    text += rule("var.build_config.scope == 'component'", [f"{COMPONENT_ROOT_DOC}.md"], "The root of a per-component report.")
    for component in documented_components(project_root):
        condition = (
            f"'{component}' in var.build_config.components and "
            f"(var.build_config.scope == 'variant' or var.build_config.component == '{component}')"
        )
        text += rule(condition, [f"{component}/doc/**", f"{MOUNT_AT}/{component}/**"], component)
    hand_written = project_root / HAND_WRITTEN_RULES
    if hand_written.is_file():
        import tomllib

        for entry in tomllib.loads(hand_written.read_text(encoding="utf-8")).get("source", {}).get("variant_sources", []):
            if set(entry) != {"if", "files"} or not isinstance(entry["files"], list):
                raise ValueError(f"{HAND_WRITTEN_RULES}: a rule has exactly `if` and `files`, got {sorted(entry)}")
            text += rule(entry["if"].replace('"', "'"), entry["files"], f"from {HAND_WRITTEN_RULES}")
    return text


def selection_toml(
    variant_data_file: Path, variant: str, kit: str, build_dir: Path | None, root_doc: str | None = None
) -> str:
    """One selection: which variant data file a reader evaluates, and which build it shows.

    The mount's condition names the build's own variant and kit. A reader pointed
    at another variant's data then reads none of this build's pages, instead of
    showing them as that variant's.
    """
    text = GENERATED_HEADER + f'\n[needs]\nvariant_data_file = "{variant_data_file.resolve().as_posix()}"\n'
    if root_doc:
        text += f'\n[project]\nroot_doc = "{root_doc}"\n'
    if build_dir is None:
        text += "\n[source]\nmounts = []\n"
    else:
        condition = f'var.build_config.target == "reports" and var.build_config.variant == "{variant}" and var.build_config.kit == "{kit}"'
        included = ", ".join(f'"{pattern}"' for pattern in MOUNTED_PAGES)
        text += (
            "\n[[source.mounts]]\n"
            f'dir = "{build_dir.resolve().as_posix()}"\n'
            f'mount_at = "{MOUNT_AT}"\n'
            f"include = [{included}]\n"
            "gitignore = false\n"
            f"if = '{condition}'\n"
        )
    return text


def write_text_if_changed(path: Path, text: str) -> bool:
    """Write only when the content changes, so a reader's cache stays valid."""
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def write_rules(project_root: Path) -> Path:
    path = project_root / RULES_FILE
    write_text_if_changed(path, rules_toml(project_root))
    return path


def write_selection(project_root: Path, variant: str, kit: str, target: str, build_dir: Path | None) -> None:
    """Select one cell: build/selection.toml, and one file per spl-core run of the build.

    Every documentation run spl-core starts in the build names its own file
    (`-D spl_selection=...`, SPL_SPHINX_OPTIONS in CMakeLists.txt), so two builds'
    reports can be built side by side. build/selection.toml is what the IDE and a
    bare run read; it is written last, so it names the build configured last.
    """
    _remove_stale_selection(project_root)
    if build_dir is not None:
        runs = build_dir / "selection"
        for shape in TARGETS:
            write_text_if_changed(
                runs / f"{shape}.toml",
                selection_toml(cell_path(project_root, variant, kit, shape), variant, kit, build_dir),
            )
            for component in reported_components(project_root, variant, kit):
                write_text_if_changed(
                    runs / component / f"{shape}.toml",
                    selection_toml(
                        cell_path(project_root, variant, kit, shape, component), variant, kit, build_dir, COMPONENT_ROOT_DOC
                    ),
                )
    write_text_if_changed(
        project_root / SELECTION_FILE,
        selection_toml(cell_path(project_root, variant, kit, target), variant, kit, build_dir),
    )


def _remove_stale_selection(project_root: Path) -> None:
    """Remove what earlier versions of this script wrote to select a variant.

    `build/autoconf.json` was the pointer, and `generated` a link (a junction on
    Windows) to the configured build directory. Nothing reads either any more,
    and a stale link would still lead Sphinx's walk into a build directory.
    """
    pointer = project_root / "build" / "autoconf.json"
    if pointer.is_file():
        pointer.unlink()
    _remove_link(project_root / MOUNT_AT)


def _remove_link(path: Path) -> None:
    """Remove the `generated` link earlier versions made, never what it led to.

    A real directory is only removed when it is the placeholder those versions
    left where no link could be made (it holds `NO_SYMLINK`); anything else there
    is somebody's, and stays.
    """
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.is_junction():
        path.rmdir()  # removes the junction itself, not the directory it leads to
    elif path.is_dir() and (path / "NO_SYMLINK").is_file():
        shutil.rmtree(path)


#: Dropped into every directory this script owns. `build/` itself gets one too,
#: because that is the directory somebody is most likely to open and edit in.
GENERATED_MARKER = (
    "Written by tools/variant_data.py. Everything under build/ is generated\n"
    "output: nobody edits it, neither a person nor an assistant.\n"
)


def mark_generated(project_root: Path) -> None:
    for directory in (project_root / "build", project_root / "build" / "variants"):
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "GENERATED").write_text(GENERATED_MARKER, encoding="utf-8")


def _check(project_root: Path, selected: list[str]) -> int:
    """Regenerate in memory and report cells that are missing or stale.

    The gate this serves is "the variant data on disk is what the sources say
    it is". It has to be a comparison rather than a regeneration, because a
    regeneration always passes: it would simply overwrite the drift it was
    meant to catch and report success.
    """
    stale: list[str] = []
    expected_files: list[tuple[Path, str]] = []
    for variant in selected:
        for kit, target, component in cells(project_root, variant):
            data = variant_data(project_root, variant, kit, target, component)
            expected_files.append(
                (cell_path(project_root, variant, kit, target, component), json.dumps(data, indent=2, sort_keys=True) + "\n")
            )
    expected_files.append((project_root / RULES_FILE, rules_toml(project_root)))
    for path, expected in expected_files:
        rel = path.relative_to(project_root)
        if not path.exists():
            stale.append(f"{rel}: missing")
        elif path.read_text(encoding="utf-8") != expected:
            stale.append(f"{rel}: stale")

    if stale:
        print("variant data is not up to date:", file=sys.stderr)
        for line in stale:
            print(f"  {line}", file=sys.stderr)
        print("\nrun: python tools/variant_data.py --all", file=sys.stderr)
        return 1

    print(f"variant data up to date ({len(expected_files) - 1} cells, and the rules)")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--project-root", type=Path, default=PROJECT_ROOT)
    parser.add_argument("--all", action="store_true", help="generate the whole matrix")
    parser.add_argument("--variant", help="variant name, e.g. Disco or Base/Dev")
    parser.add_argument("--kit", choices=KITS, default="prod")
    parser.add_argument("--target", choices=TARGETS, default="docs")
    parser.add_argument(
        "--current",
        action="store_true",
        help=f"also select the cell: write {SELECTION_FILE}",
    )
    parser.add_argument(
        "--build-dir",
        type=Path,
        help="CMake binary dir of the selected cell: mounted at `generated`, with one selection file per run",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write: compare what would be generated against what is on disk",
    )
    args = parser.parse_args(argv)

    project_root: Path = args.project_root.resolve()

    if not args.all and not args.variant:
        parser.error("either --all or --variant is required")

    selected = variant_names(project_root) if args.all else [args.variant]

    if args.check:
        return _check(project_root, selected)

    written = 0
    for variant in selected:
        for kit, target, component in cells(project_root, variant):
            data = variant_data(project_root, variant, kit, target, component)
            write_cell(project_root, variant, kit, target, data, component)
            written += 1
    print(f"wrote {written} variant data files")

    mark_generated(project_root)
    print(f"wrote {write_rules(project_root).relative_to(project_root)}")

    if args.current or not args.all:
        variant = args.variant or selected[0]
        write_selection(project_root, variant, args.kit, args.target, args.build_dir)
        print(f"selected {variant} / {args.kit} / {args.target}" + (f" in {args.build_dir}" if args.build_dir else ""))

    return 0


if __name__ == "__main__":
    sys.exit(main())
